FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

WORKDIR /usr/src/app

RUN apk add curl grep

RUN curl https://api.github.com/repos/balena-io/wifi-connect/releases/latest -s \
      | grep -hoP 'browser_download_url": "\K.*%%RESIN_ARCH%%\.tar\.gz' \
      | xargs -n1 curl -Ls \
      | tar -xvz -C /usr/src/app/

RUN apk del curl grep

# Move app to filesystem
COPY ./app/start.sh ./

# Start app
CMD ["bash", "start.sh"]
