env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
plugins:
  - lodash
  - jsdoc
extends: 'eslint:recommended'
settings:
  jsdoc:
    additionalTagNames:
      customTags:
        - fulfil
rules:

  # Possible Errors

  no-cond-assign:
    - error
  no-console:
    - off
  no-constant-condition:
    - error
  no-control-regex:
    - error
  no-debugger:
    - error
  no-dupe-args:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - error
  no-empty-character-class:
    - error
  no-ex-assign:
    - error
  no-extra-boolean-cast:
    - error
  no-extra-parens:
    - error
  no-extra-semi:
    - error
  no-func-assign:
    - error
  no-inner-declarations:
    - error
    - both
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - error
  no-negated-in-lhs:
    - error
  no-obj-calls:
    - error
  no-prototype-builtins:
    - error
  no-regex-spaces:
    - error
  no-sparse-arrays:
    - error
  no-template-curly-in-string:
    - error
  no-unexpected-multiline:
    - error
  no-unreachable:
    - error
  no-unsafe-finally:
    - error
  use-isnan:
    - error
  valid-jsdoc:
    - error
    - requireReturn: false
      requireReturnDescription: false
      requireReturnType: true
      requireParamDescription: true
      preferType:
        boolean: "Boolean"
        number: "Number"
        object: "Object"
        string: "String"
        array: "Array"
      prefer:
        arg: "param"
        return: "returns"
  valid-typeof:
    - error

  # Best Practices

  accessor-pairs:
    - error
  array-callback-return:
    - error
  block-scoped-var:
    - error
  class-methods-use-this:
    - error
  complexity:
    - off
  consistent-return:
    - error
  curly:
    - error
  default-case:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
  guard-for-in:
    - error
  no-alert:
    - error
  no-caller:
    - error
  no-case-declarations:
    - error
  no-div-regex:
    - error
  no-else-return:
    - error
  no-empty-function:
    - error
  no-empty-pattern:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-extra-label:
    - error
  no-fallthrough:
    - error
  no-floating-decimal:
    - error
  no-global-assign:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-iterator:
    - error
  no-labels:
    - error
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - error
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-native-reassign:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-octal:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - error
  no-proto:
    - error
  no-redeclare:
    - error
  no-restricted-properties:
    - error
    - property: __proto__
  no-return-assign:
    - error
  no-return-await:
    - error
  no-script-url:
    - error
  no-self-assign:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-unmodified-loop-condition:
    - error
  no-unused-expressions:
    - error
  no-unused-labels:
    - error
  no-useless-call:
    - error
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-void:
    - error
  no-warning-comments:
    - off
  no-with:
    - error
  radix:
    - error
  vars-on-top:
    - off
  wrap-iife:
    - error
    - outside
  yoda:
    - error

  # Strict mode

  strict:
    - error
    - global

  # Variables

  init-declarations:
    - error
    - always
  no-catch-shadow:
    - error
  no-delete-var:
    - error
  no-label-var:
    - error
  no-restricted-globals:
    - error
    - event
  no-shadow:
    - error
  no-shadow-restricted-names:
    - error
  no-undef:
    - error
  no-undef-init:
    - error
  no-undefined:
    - error
  no-unused-vars:
    - error
  no-use-before-define:
    - error

  # NodeJS and CommonJS

  callback-return:
    - error
  global-require:
    - off
  handle-callback-err:
    - error
  no-mixed-requires:
    - error
  no-new-require:
    - error
  no-path-concat:
    - error
  no-process-env:
    - off
  no-process-exit:
    - off
  no-sync:
    - off

  # Stylistic Issues

  array-bracket-spacing:
    - error
    - always
  block-spacing:
    - error
  brace-style:
    - error
    - 1tbs
  camelcase:
    - error
  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true
  comma-dangle:
    - error
    - never
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  consistent-this:
    - error
    - self
  eol-last:
    - error
  func-call-spacing:
    - error
    - never
  func-name-matching:
    - error
    - always
  func-names:
    - error
    - never
  func-style:
    - error
    - expression
  id-blacklist:
    - error
  id-length:
    - error
    - min: 2
      exceptions:
        - "_"
  indent:
    - error
    - 2
    - SwitchCase: 1
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - error
    - before: true
      after: true
  line-comment-position:
    - error
    - position: above
  linebreak-style:
    - error
    - unix
  lines-around-comment:
    - error
    - beforeBlockComment: true
      afterBlockComment: false
      beforeLineComment: true
      afterLineComment: false
      allowBlockStart: true
      allowBlockEnd: false
      allowObjectStart: true
      allowObjectEnd: false
      allowArrayStart: true
      allowArrayEnd: false
  lines-around-directive:
    - error
    - always
  max-len:
    - error
    - code: 130
      comments: 150
      ignoreComments: false
      ignoreTrailingComments: false
      ignoreUrls: true
  max-params:
    - off
  max-statements-per-line:
    - error
    - max: 1
  multiline-ternary:
    - error
    - never
  new-cap:
    - error
  new-parens:
    - error
  newline-per-chained-call:
    - off
  no-array-constructor:
    - error
  no-bitwise:
    - error
  no-continue:
    - error
  no-inline-comments:
    - error
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-multi-assign:
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
      maxBOF: 0
  no-negated-condition:
    - error
  no-nested-ternary:
    - error
  no-new-object:
    - error
  no-plusplus:
    - error
  no-restricted-syntax:
    - error
    - WithStatement
    - ForInStatement
  no-spaced-func:
    - error
  no-tabs:
    - error
  no-trailing-spaces:
    - error
  no-underscore-dangle:
    - error
    - allowAfterThis: false
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - error
    - minProperties: 1
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
  one-var-declaration-per-line:
    - error
    - always
  one-var:
    - error
    - never
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - classes: always
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        ClassDeclaration: true
        MethodDefinition: true
        ArrowFunctionExpression: true
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks:
    - error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  spaced-comment:
    - error
    - always
  template-tag-spacing:
    - error
    - always
  unicode-bom:
    - error

  # ECMAScript 6

  arrow-body-style:
    - error
    - always
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  constructor-super:
    - error
  generator-star-spacing:
    - error
    - before: true
      after: false
  no-class-assign:
    - error
  no-confusing-arrow:
    - error
  no-const-assign:
    - error
  no-dupe-class-members:
    - error
  no-duplicate-imports:
    - error
  no-new-symbol:
    - error
  no-this-before-super:
    - error
  no-useless-computed-key:
    - error
  no-useless-constructor:
    - error
  no-useless-rename:
    - error
  no-var:
    - error
  object-shorthand:
    - error
    - always
  prefer-const:
    - error
  prefer-reflect:
    - error
  prefer-spread:
    - error
  prefer-numeric-literals:
    - error
  prefer-rest-params:
    - error
  prefer-template:
    - error
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: false
  require-yield:
    - error
  rest-spread-spacing:
    - error
  template-curly-spacing:
    - error
    - never
  symbol-description:
    - error
  yield-star-spacing:
    - error
    - before: true
      after: false

  # Lodash

  lodash/chain-style:
    - error
    - explicit
  lodash/identity-shorthand:
    - error
    - always
  lodash/import-scope:
    - error
    - full
  lodash/matches-prop-shorthand:
    - error
    - always
  lodash/matches-shorthand:
    - error
    - always
  lodash/no-commit:
    - error
  lodash/path-style:
    - error
    - array
  lodash/prefer-compact:
    - error
  lodash/prefer-filter:
    - error
    - 5
  lodash/prefer-flat-map:
    - error
  lodash/prefer-invoke-map:
    - error
  lodash/prefer-map:
    - error
  lodash/prefer-reject:
    - error
  lodash/prefer-thru:
    - error
  lodash/prefer-wrapper-method:
    - error
  lodash/prop-shorthand:
    - error
    - always
  lodash/prefer-constant:
    - error
    - true
    - true
  lodash/prefer-get:
    - error
    - 2
  lodash/prefer-includes:
    - error
    - includeNative: true
  lodash/prefer-is-nil:
    - error
  lodash/prefer-lodash-chain:
    - error
  lodash/prefer-lodash-method:
    - error
  lodash/prefer-lodash-typecheck:
    - error
  lodash/prefer-matches:
    - error
    - 3
  lodash/prefer-noop:
    - error
  lodash/prefer-over-quantifier:
    - error
  lodash/prefer-startswith:
    - error
  lodash/prefer-times:
    - error

  # JSDoc

  jsdoc/check-param-names:
    - error
  jsdoc/check-tag-names:
    - error
  jsdoc/newline-after-description:
    - error
  jsdoc/require-example:
    - error
  jsdoc/require-hyphen-before-param-description:
    - error
  jsdoc/require-param:
    - error
  jsdoc/require-param-description:
    - error
  jsdoc/require-param-type:
    - error
  jsdoc/require-returns-type:
    - error
