scss_files: 'lib/gui/scss/**/*.scss'

linters:
  Comment:
    enabled: false
  ColorVariable:
    enabled: false
  ImportantRule:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
