name: test all
on:
  push:
    branches:
      - "rdbox-main"
      - "develop"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_push
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      - name: Checkout_pr
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          submodules: recursive
      - name: Build
        run: bash ./rdbox-utils.bash build all
      - name: Test all
        run: bash ./rdbox-utils.bash run test